### ISSUE TITLE
Block Merge on Needs Work Labels

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#138]
## Proposal

If a PR has do-not-merge, or `needs *`, let's explicitly flag the PR as blocked from merging. This is intended to relieve reviewers of responsibility to enforce basic workflow rules, though it's still up to reviewers to add the label as needed.

When a `needs work`, `needs tests`, `needs decision record`, `needs docs`, or `do not merge` label is applied, we want to add a build failure. If the label is removed, we want the build to succeed. We do not want to prevent other tests from running: we want to know if tests are passing as a higher priority than this check.

I scratched together this starting place based on a few minutes of research:

```yaml
on:
  pull_request:
    branches:
      - main
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Blocking Label - needs *"
        if: contains( github.event.pull_request.labels.*.name, 'needs')
        run:
          - echo "PR has label '${{github.event.pull_request.labels.*.name}}', blocking merge"
          - exit 1
      - name: "Blocking Label - do not merge"
        if: contains( github.event.pull_request.labels.*.name, 'do not merge')
        run:
          - echo "PR has label 'do not merge', blocking merge"
          - exit 1
```

## Future Considerations/Stretch Goals

The following ideas have not been fully considered, but are included for context. Pursuing them should probably be decided in maintainer team discussion.

* Consider if we need these labels applied by default when PRs are opened, perhaps via a PR template
* Auto-detect docs, tests, and decision record changes and remove the label if present. Evaluating if those changes are quality might be considered a review task
* In the case of the `needs *` issues, post a comment to the issue explaining what needs to happen, linking to CONTRIBUTING.md.
