### ISSUE TITLE
Modernize Cloud Build YAML with 'script' property

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#790]
## Proposal

The current Cloud Build YAML implementation uses the "original" syntax for running shell scripts in containers, which closely matches container entrypoint configuration. Since that structure is not a natural developer experience for people that don't regularly work with containers, there is now a `script` property that allows something more akin to the experience of running scripts in GitHub Workflows.

Let's update the Cloud Build YAML to use that more natural pattern. This seems like a low risk change that boosts readability.

* **Example of a Cloud Build config to change:** https://github.com/GoogleCloudPlatform/emblem/blob/main/ops/unit-tests.cloudbuild.yaml#L23
* **Documentation on Script tag:** https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts 

### Before

```yaml
 # Install test requirements
 - id: "Install Pytest"
   name: python:3.11-slim
   dir: ${_DIR}
   entrypoint: pip
   args: ["install", "-r", "requirements-test.txt", "--user"]
```

### After

```yaml
# Install test requirements
 - id: "Install Pytest"
   name: python:3.11-slim
   dir: ${_DIR}
   script: pip install -r requirements-test.txt --user
```
